name: aws_s3_android
description: android implementation of aws_s3_plugin.
version: 0.0.1
repository: https://github.com/FaKenKoala/aws_s3_plugin/tree/main/aws_s3_android

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  aws_s3_platform_interface:
    path: /Users/wombat/FlutterProjects/object_storage_service/aws_s3_plugin/aws_s3_platform_interface
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  plugin:
    implements: aws_s3_plugin
    platforms:
      android:
        package: com.wombat.aws_s3
        pluginClass: AwsS3Plugin
        dartPluginClass: AwsS3Android
