name: aws_s3_platform_interface
description: aws s3 platform interface.
version: 0.0.1
homepage: https://github.com/FaKenKoala/aws_s3_plugin/tree/main/aws_s3_platform_interface

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies: 
  plugin_platform_interface: ^2.1.2
  