name: aws_s3_platform_interface
description: aws s3 platform interface.
version: 0.0.1
repository: https://github.com/FaKenKoala/aws_s3_plugin/tree/main/aws_s3_platform_interface

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.5.0
  plugin_platform_interface: ^2.1.2
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
